# fly.toml app configuration file generated for quiet-frog-8512 on 2023-07-29T09:27:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-frog-8512"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
