# fly.toml app configuration file generated for broken-sky-4522 on 2023-07-29T12:02:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-sky-4522"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
