const styles = {
  container: "container mx-auto px-4",
  heading: "text-3xl font-bold text-center pt-10 font-serif",
  section: "w-full bg-gray-300 py-4 px-8",
  sectionHeading: "text-2xl font-bold text-center mb-6",
  productTitle: "text-xl font-semibold text-gray-800 mb-4",
  price: "font-medium text-lg text-pink-600 pl-3 mt--4px",
  shopName: "text-xl text-red-700 font-bold pb-4",
  activeIndicator: "absolute bottom--27% left-0 h-3 w-full bg-pink-500",
  button: "w-40 h-12 flex items-center justify-center rounded-md bg-[#3321c8] text-white text-lg font-semibold",
  cartButton: "px-4 h-10 rounded-lg bg-pink-200 flex items-center justify-center cursor-pointer relative",
  cartButtonIcon: "w-6 h-6 bg-pink-500 absolute -left-5 rounded-full flex items-center justify-center text-white",
  cartButtonText: "text-pink-600 text-sm font-semibold",
  input: "w-full border p-2 rounded-lg bg-white",
  activeStatus: "w-4 h-4 rounded-full absolute top-0 right-0 bg-pink-500",
  normalFlex: "flex items-center",
  navbar: "flex justify-between py-4",
  navLink: "text-white font-semibold ml-6 hover:text-pink-500",
  navLogo: "text-white font-bold text-3xl",
  faqDiv: "border-b border-gray-200 pb-4",
  faqButton: "flex items-center justify-between w-full",
  faqButtonIcon: "h-6 w-6 text-gray-500",
  faqButtonText: "text-lg font-medium text-gray-900",
  faqAnswer: "mt-4",
  faqText: "text-base text-gray-500",
  dashboardHeaderFiIcons: "mx-5 cursor-pointer",
};

export default styles;